services:
  postgres_DB:
    container_name: postgres_DB
    image: postgres:17.5
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=electronics_warehouse
    volumes:
      - ./db/postgres_data/:/var/lib/postgresql/data

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    ports:
      - '5000:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=huyentrang@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345
