services:
  postgres_DB:
    container_name: postgres_DB
    image: postgres:17
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=electronics_warehouse
    volumes:
      - ./db/postgres_data/:/var/lib/postgresql/data
