# Generated by Django 5.1.3 on 2025-05-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('idSanPham', models.CharField(primary_key=True, serialize=False)),
                ('idDanhMuc', models.CharField()),
                ('tenSanPham', models.CharField()),
                ('soLuong', models.BigIntegerField()),
                ('moTa', models.CharField()),
                ('trangThai', models.CharField(default='Không hỏng')),
                ('hinhAnh', models.CharField()),
                ('donViTinh', models.CharField(default='Cái')),
            ],
        ),
    ]
