# Generated by Django 5.1.3 on 2025-06-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id_san_pham', models.CharField(db_column='id_san_pham', max_length=5, primary_key=True, serialize=False)),
                ('id_danh_muc', models.TextField(db_column='id_danh_muc')),
                ('ten_san_pham', models.TextField(db_column='ten_san_pham')),
                ('so_luong', models.BigIntegerField(db_column='so_luong')),
                ('mo_ta', models.TextField(db_column='mo_ta')),
                ('trang_thai', models.TextField(db_column='trang_thai', default='Không hỏng')),
                ('hinh_anh', models.TextField(db_column='hinh_anh')),
                ('don_vi_tinh', models.TextField(db_column='don_vi_tinh', default='Cái')),
            ],
            options={
                'db_table': 'san_pham',
                'constraints': [models.CheckConstraint(condition=models.Q(('so_luong__gt', 0)), name='so_luong_lon_hon_0')],
            },
        ),
        migrations.CreateModel(
            name='DSYeuCauXuatKho',
            fields=[
                ('id_yeu_cau_xuat', models.CharField(db_column='id_yeu_cau_xuat', max_length=5, primary_key=True, serialize=False)),
                ('thoi_gian', models.DateTimeField(db_column='thoi_gian')),
                ('ghi_chu', models.TextField(db_column='ghi_chu')),
                ('trang_thai', models.TextField(db_column='trang_thai')),
                ('loai', models.TextField(db_column='loai')),
                ('id_nhan_vien_yc', models.ForeignKey(db_column='id_nhan_vien_yc', on_delete=django.db.models.deletion.CASCADE, to='accounts.taikhoan')),
            ],
            options={
                'db_table': 'ds_yeu_cau_xuat_kho',
                'constraints': [models.CheckConstraint(condition=models.Q(('trang_thai__in', ['Chờ duyệt', 'Đã duyệt', 'Đã xuất', 'Từ chối'])), name='trang_thai_hop_le'), models.CheckConstraint(condition=models.Q(('loai__in', ['Xuất hàng hỏng', 'Hàng để bán'])), name='loai_hop_le')],
            },
        ),
        migrations.CreateModel(
            name='HangXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_yeu_cau_xuat', models.CharField(db_column='id_yeu_cau_xuat', max_length=5)),
                ('so_luong', models.IntegerField(db_column='so_luong')),
                ('ghi_chu', models.TextField(db_column='ghi_chu')),
                ('thoi_gian_xuat', models.DateTimeField(db_column='thoi_gian_xuat')),
                ('id_nhan_vien_xuat', models.ForeignKey(db_column='id_nhan_vien_xuat', on_delete=django.db.models.deletion.CASCADE, to='accounts.taikhoan')),
                ('id_san_pham', models.ForeignKey(db_column='id_san_pham', on_delete=django.db.models.deletion.CASCADE, to='sale_staff.sanpham')),
            ],
            options={
                'db_table': 'hang_xuat_kho',
                'constraints': [models.UniqueConstraint(fields=('id_yeu_cau_xuat', 'id_san_pham'), name='primary_key_id_yc_id_san_pham')],
            },
        ),
        migrations.CreateModel(
            name='ChiTietYeuCauXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_yeu_cau_xuat', models.CharField(db_column='id_yeu_cau_xuat', max_length=5)),
                ('so_luong', models.IntegerField(db_column='so_luong')),
                ('ghi_chu', models.TextField(db_column='ghi_chu')),
                ('id_san_pham', models.ForeignKey(db_column='id_san_pham', on_delete=django.db.models.deletion.CASCADE, to='sale_staff.sanpham')),
            ],
            options={
                'db_table': 'chi_tiet_yeu_cau_xuat',
                'constraints': [models.UniqueConstraint(fields=('id_yeu_cau_xuat', 'id_san_pham'), name='pk_ctycx_composite')],
            },
        ),
    ]
