# Generated by Django 5.1.3 on 2025-06-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSYeuCauXuatKho',
            fields=[
                ('idYeuCauXuat', models.CharField(db_column='id_yeu_cau_xuat', max_length=5, primary_key=True, serialize=False)),
                ('thoiGian', models.DateTimeField(db_column='thoi_gian')),
                ('ghiChu', models.TextField(db_column='ghi_chu')),
                ('trangThai', models.TextField(db_column='trang_thai')),
                ('loai', models.TextField(db_column='loai')),
            ],
            options={
                'db_table': 'ds_yeu_cau_xuat_kho',
                'constraints': [models.CheckConstraint(condition=models.Q(('trangThai__in', ['Chờ duyệt', 'Đã duyệt', 'Đã nhập kho', 'Từ chối'])), name='trang_thai_hop_le'), models.CheckConstraint(condition=models.Q(('loai__in', ['Xuất hàng hỏng', 'Hàng để bán'])), name='loai_hop_le')],
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('idSanPham', models.CharField(db_column='id_san_pham', max_length=5, primary_key=True, serialize=False)),
                ('idDanhMuc', models.TextField(db_column='id_danh_muc')),
                ('tenSanPham', models.TextField(db_column='ten_san_pham')),
                ('soLuong', models.BigIntegerField(db_column='so_luong')),
                ('moTa', models.TextField(db_column='mo_ta')),
                ('trangThai', models.TextField(db_column='trang_thai', default='Không hỏng')),
                ('hinhAnh', models.TextField(db_column='hinh_anh')),
                ('donViTinh', models.TextField(db_column='don_vi_tinh', default='Cái')),
            ],
            options={
                'db_table': 'san_pham',
                'constraints': [models.CheckConstraint(condition=models.Q(('soLuong__gt', 0)), name='so_luong_lon_hon_0')],
            },
        ),
        migrations.CreateModel(
            name='HangXuatKho',
            fields=[
                ('idYeuCauXuat', models.CharField(db_column='id_yeu_cau_xuat', max_length=5, primary_key=True, serialize=False)),
                ('soLuong', models.IntegerField(db_column='so_luong')),
                ('ghiChu', models.TextField(db_column='ghi_chu')),
                ('thoiGianXuat', models.DateTimeField(db_column='thoi_gian_xuat')),
                ('idSanPham', models.ForeignKey(db_column='id_san_pham', on_delete=django.db.models.deletion.CASCADE, to='sale_staff.sanpham')),
            ],
            options={
                'db_table': 'hang_xuat_kho',
            },
        ),
        migrations.CreateModel(
            name='ChiTietYeuCauXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idYeuCauXuat', models.CharField(db_column='id_yeu_cau_xuat', max_length=5)),
                ('soLuong', models.IntegerField(db_column='so_luong')),
                ('ghiChu', models.TextField(db_column='ghi_chu')),
                ('idSanPham', models.ForeignKey(db_column='id_san_pham', on_delete=django.db.models.deletion.CASCADE, to='sale_staff.sanpham')),
            ],
            options={
                'db_table': 'chi_tiet_yeu_cau_xuat',
                'constraints': [models.UniqueConstraint(fields=('idYeuCauXuat', 'idSanPham'), name='pk_ctycx_composite')],
            },
        ),
    ]
