# Generated by Django 5.1.3 on 2025-06-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_staff', '0001_create_san_pham_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='donViTinh',
            field=models.TextField(default='Cái'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='hinhAnh',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='idDanhMuc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='idSanPham',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='moTa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='tenSanPham',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThai',
            field=models.TextField(default='Không hỏng'),
        ),
        migrations.AlterModelTable(
            name='sanpham',
            table='san_pham',
        ),
    ]
