# Generated by Django 5.1.3 on 2025-06-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sale_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsyeucauxuatkho',
            name='id_nhan_vien_duyet',
            field=models.ForeignKey(db_column='id_nhan_vien_duyet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeu_cau_xuat_duyet', to='accounts.taikhoan'),
        ),
    ]
