# Generated by Django 5.1.3 on 2025-06-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chitietyeucauxuat',
            old_name='ghiChu',
            new_name='ghi_chu',
        ),
        migrations.RenameField(
            model_name='chitietyeucauxuat',
            old_name='idSanPham',
            new_name='id_san_pham',
        ),
        migrations.RenameField(
            model_name='chitietyeucauxuat',
            old_name='idYeuCauXuat',
            new_name='id_yeu_cau_xuat',
        ),
        migrations.RenameField(
            model_name='chitietyeucauxuat',
            old_name='soLuong',
            new_name='so_luong',
        ),
        migrations.RenameField(
            model_name='dsyeucauxuatkho',
            old_name='ghiChu',
            new_name='ghi_chu',
        ),
        migrations.RenameField(
            model_name='dsyeucauxuatkho',
            old_name='idYeuCauXuat',
            new_name='id_yeu_cau_xuat',
        ),
        migrations.RenameField(
            model_name='dsyeucauxuatkho',
            old_name='thoiGian',
            new_name='thoi_gian',
        ),
        migrations.RenameField(
            model_name='dsyeucauxuatkho',
            old_name='trangThai',
            new_name='trang_thai',
        ),
        migrations.RenameField(
            model_name='hangxuatkho',
            old_name='ghiChu',
            new_name='ghi_chu',
        ),
        migrations.RenameField(
            model_name='hangxuatkho',
            old_name='idSanPham',
            new_name='id_san_pham',
        ),
        migrations.RenameField(
            model_name='hangxuatkho',
            old_name='idYeuCauXuat',
            new_name='id_yeu_cau_xuat',
        ),
        migrations.RenameField(
            model_name='hangxuatkho',
            old_name='soLuong',
            new_name='so_luong',
        ),
        migrations.RenameField(
            model_name='hangxuatkho',
            old_name='thoiGianXuat',
            new_name='thoi_gian_xuat',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='donViTinh',
            new_name='don_vi_tinh',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='hinhAnh',
            new_name='hinh_anh',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='idDanhMuc',
            new_name='id_danh_muc',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='idSanPham',
            new_name='id_san_pham',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='moTa',
            new_name='mo_ta',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='soLuong',
            new_name='so_luong',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='tenSanPham',
            new_name='ten_san_pham',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='trangThai',
            new_name='trang_thai',
        ),
    ]
