# Generated by Django 5.1.3 on 2025-06-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_staff', '0002_alter_dsyeucauxuatkho_id_nhan_vien_duyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietyeucauxuat',
            name='so_luong_thuc',
            field=models.IntegerField(db_column='so_luong_thuc', null=True),
        ),
    ]
