# Generated by Django 5.1.3 on 2025-06-01 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_staff', '0002_alter_sanpham_donvitinh_alter_sanpham_hinhanh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietYeuCauXuat',
            fields=[
                ('idYeuCauXuat', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('soLuong', models.IntegerField()),
                ('ghiChu', models.TextField()),
                ('idSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_staff.sanpham')),
            ],
            options={
                'db_table': 'chi_tiet_yeu_cau_xuat',
            },
        ),
        migrations.CreateModel(
            name='DSYeuCauXuatKho',
            fields=[
                ('idYeuCauXuat', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('thoiGian', models.DateTimeField()),
                ('ghiChu', models.TextField()),
                ('trangThai', models.TextField()),
                ('loai', models.TextField()),
            ],
            options={
                'db_table': 'ds_yeu_cau_xuat_kho',
                'constraints': [models.CheckConstraint(condition=models.Q(('trangThai__in', ['Chờ duyệt', 'Đã duyệt', 'Đã nhập kho', 'Từ chối'])), name='trang_thai_hop_le'), models.CheckConstraint(condition=models.Q(('loai__in', ['Xuất hàng hỏng', 'Hàng để bán'])), name='loai_hop_le')],
            },
        ),
        migrations.CreateModel(
            name='HangXuatKho',
            fields=[
                ('idYeuCauXuat', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('soLuong', models.IntegerField()),
                ('ghiChu', models.TextField()),
                ('thoiGianXuat', models.DateTimeField()),
                ('idSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_staff.sanpham')),
            ],
            options={
                'db_table': 'hang_xuat_kho',
            },
        ),
    ]
