# Generated by Django 5.1.3 on 2025-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_staff', '0003_create_ChiTietYeuCauXuat_DsYeuCauXuatKho_HangXuatKho_tables'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sanpham',
            constraint=models.CheckConstraint(condition=models.Q(('soLuong__gt', 0)), name='so_luong_lon_hon_0'),
        ),
    ]
