# Generated by Django 5.2 on 2025-06-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_staff', '0004_remove_dsyeucauxuatkho_trang_thai_hop_le_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangxuatkho',
            name='id_yeu_cau_xuat',
            field=models.CharField(db_column='id_yeu_cau_xuat'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='id_san_pham',
            field=models.CharField(db_column='id_san_pham', primary_key=True, serialize=False),
        ),
    ]
