# Generated by Django 5.1.3 on 2025-06-01 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_staff', '0004_create_soLuongSP_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietyeucauxuat',
            name='ghiChu',
            field=models.TextField(db_column='ghi_chu'),
        ),
        migrations.AlterField(
            model_name='chitietyeucauxuat',
            name='idSanPham',
            field=models.ForeignKey(db_column='id_san_pham', on_delete=django.db.models.deletion.CASCADE, to='sale_staff.sanpham'),
        ),
        migrations.AlterField(
            model_name='chitietyeucauxuat',
            name='idYeuCauXuat',
            field=models.CharField(db_column='id_yeu_cau_xuat', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chitietyeucauxuat',
            name='soLuong',
            field=models.IntegerField(db_column='so_luong'),
        ),
        migrations.AlterField(
            model_name='dsyeucauxuatkho',
            name='ghiChu',
            field=models.TextField(db_column='ghi_chu'),
        ),
        migrations.AlterField(
            model_name='dsyeucauxuatkho',
            name='idYeuCauXuat',
            field=models.CharField(db_column='id_yeu_cau_xuat', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dsyeucauxuatkho',
            name='loai',
            field=models.TextField(db_column='loai'),
        ),
        migrations.AlterField(
            model_name='dsyeucauxuatkho',
            name='thoiGian',
            field=models.DateTimeField(db_column='thoi_gian'),
        ),
        migrations.AlterField(
            model_name='dsyeucauxuatkho',
            name='trangThai',
            field=models.TextField(db_column='trang_thai'),
        ),
        migrations.AlterField(
            model_name='hangxuatkho',
            name='ghiChu',
            field=models.TextField(db_column='ghi_chu'),
        ),
        migrations.AlterField(
            model_name='hangxuatkho',
            name='idSanPham',
            field=models.ForeignKey(db_column='id_san_pham', on_delete=django.db.models.deletion.CASCADE, to='sale_staff.sanpham'),
        ),
        migrations.AlterField(
            model_name='hangxuatkho',
            name='idYeuCauXuat',
            field=models.CharField(db_column='id_yeu_cau_xuat', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hangxuatkho',
            name='soLuong',
            field=models.IntegerField(db_column='so_luong'),
        ),
        migrations.AlterField(
            model_name='hangxuatkho',
            name='thoiGianXuat',
            field=models.DateTimeField(db_column='thoi_gian_xuat'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='donViTinh',
            field=models.TextField(db_column='don_vi_tinh', default='Cái'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='hinhAnh',
            field=models.TextField(db_column='hinh_anh'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='idDanhMuc',
            field=models.TextField(db_column='id_danh_muc'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='idSanPham',
            field=models.CharField(db_column='id_san_pham', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='moTa',
            field=models.TextField(db_column='mo_ta'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='soLuong',
            field=models.BigIntegerField(db_column='so_luong'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='tenSanPham',
            field=models.TextField(db_column='ten_san_pham'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThai',
            field=models.TextField(db_column='trang_thai', default='Không hỏng'),
        ),
    ]
