# Generated by Django 5.2 on 2025-06-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_staff', '0005_alter_hangxuatkho_id_yeu_cau_xuat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietyeucauxuat',
            name='id_yeu_cau_xuat',
            field=models.CharField(db_column='id_yeu_cau_xuat'),
        ),
        migrations.AlterField(
            model_name='dsyeucauxuatkho',
            name='id_yeu_cau_xuat',
            field=models.CharField(db_column='id_yeu_cau_xuat', primary_key=True, serialize=False),
        ),
    ]
