# Generated by Django 5.1.3 on 2025-06-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id_nhan_vien', models.TextField(primary_key=True, serialize=False)),
                ('ten_nhan_vien', models.TextField()),
                ('mat_khau', models.TextField()),
                ('chuc_vu', models.TextField()),
                ('email', models.TextField()),
                ('trang_thai', models.TextField()),
                ('gioi_tinh', models.TextField()),
            ],
            options={
                'db_table': 'tai_khoan',
                'constraints': [models.CheckConstraint(condition=models.Q(('gioi_tinh__in', ['Male', 'Female'])), name='constraint_gioi_tinh'), models.CheckConstraint(condition=models.Q(('chuc_vu__in', ['Sale Staff', 'Warehouse Staff', 'Warehouse Manager', 'admin'])), name='constraint_chuc_vu')],
            },
        ),
    ]
