# Generated by Django 5.2 on 2025-06-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taikhoan',
            name='constraint_chuc_vu',
        ),
        migrations.AddConstraint(
            model_name='taikhoan',
            constraint=models.CheckConstraint(condition=models.Q(('chuc_vu__in', ['Sale Staff', 'Warehouse Staff', 'Warehouse Manager', 'Admin'])), name='constraint_chuc_vu'),
        ),
    ]
